name: Frontend testing.plone.de CI and deploy

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'

env:
  node-version: 22.x
  IMAGE_NAME_PREFIX: ghcr.io/plone/plone.de
  IMAGE_NAME_SUFFIX: frontend
  PYTHON_VERSION: "3.12"
  STACK_PARAM: latest
  STACK_NAME: testing-plone-de
  STACK_PREFIX: testing_plonede
  PUBLIC_URL: testing.plone.de
  CERTRESOLVER: le-cloudflare
  STACK_FILE: devops/stacks/testing.plone.de.yml

defaults:
  run:
    working-directory: ./frontend

jobs:
  meta:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.vars.outputs.TAG }}
      VOLTO_VERSION: ${{ steps.vars.outputs.VOLTO_VERSION }}
      PLONE_VERSION: ${{ steps.vars.outputs.PLONE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Env Vars
        working-directory: "."
        id: vars
        run: |
          echo "TAG=$(cat version.txt)" >> $GITHUB_OUTPUT
          python3 -c 'import json; data = json.load(open("frontend/package.json")); print("VOLTO_VERSION=" + data["dependencies"]["@plone/volto"])' >> $GITHUB_OUTPUT
          echo "PLONE_VERSION=$(cat backend/version.txt)" >> $GITHUB_OUTPUT
      - name: Test vars
        working-directory: "."
        run: |
          echo "TAG=${{ steps.vars.outputs.TAG }}"
          echo "VOLTO_VERSION=${{ steps.vars.outputs.VOLTO_VERSION }}"
          echo "PLONE_VERSION=${{ steps.vars.outputs.PLONE_VERSION }}"

  eslint:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'

      - name: Install packages
        run: make install

      - name: Lint
        run: yarn run lint:ci

  prettier:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Install packages
        run: make install

      - name: Run Prettier
        run: yarn run prettier

  i18n:
    if: github.ref_type == 'branch'
    name: i18n sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'

      - name: Install packages
        run: make install

      - name: Test i18n sync
        run: make i18n-ci

  unit:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'

      - name: Install packages
        run: make install

      - name: Test
        run: make test

  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [meta, eslint, prettier, i18n, unit]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME_PREFIX }}-${{ env.IMAGE_NAME_SUFFIX }}
          labels: |
            org.label-schema.docker.cmd=docker run -d -p 8080:8080 ${{ env.IMAGE_NAME_PREFIX }}-${{ env.IMAGE_NAME_SUFFIX }}:latest
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: frontend/
          file: frontend/Dockerfile
          build-args: |
            VOLTO_VERSION=${{ needs.meta.outputs.VOLTO_VERSION }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: $${{ steps.meta.outputs.labels }}

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    concurrency: deploy_testing
    needs:
      - release
    runs-on: ubuntu-latest
    environment:
      name: testing.plone.de
      url: https://testing.plone.de
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to testing.plone.de
        uses: kitconcept/docker-stack-deploy@v1.2.0
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_GHCR_READ_TOKEN }}
          remote_host: ${{ vars.DEPLOY_HOST }}
          remote_port: ${{ vars.DEPLOY_PORT }}
          remote_user: ${{ vars.DEPLOY_USER }}
          remote_private_key: ${{ secrets.DEPLOY_SSH }}
          stack_file: 'devops/stacks/testing.plone.de.yml'
          stack_name: 'testing-plone-de'
          env_file: |
            STACK_NAME=${{ env.STACK_NAME }}
            DB_HOST=${{ vars.DB_HOST }}
            DB_PORT=${{ vars.DB_PORT }}
            DB_NAME=${{ vars.DB_NAME }}
            DB_USER=${{ vars.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          deploy_timeout: 480
